### ISSUE TITLE
Theme Button Behavior

### ISSUE THREAD

**Issue by 0ME9A** [0ME9A/compressy#7]
### Description
When opening the website in private mode or after resetting local-storage data, the theme button exhibits unexpected behavior. On the first click, it does not respond, but the button icon change and on the second click, the button icon changes parallel to the current theme. In dark mode, the button should display the light theme icon, and in light mode, it should show the dark theme icon.

### Steps to Reproduce
1. Open the website in private mode or after resetting local-storage data.
2. Attempt to click the theme button.

### Expected Behavior
The theme button should respond on the first click, and the displayed icon should correspond correctly to the selected theme (light or dark).

### Actual Behavior
The theme button does not respond on the first click, but the button icon changes, displaying the incorrect theme representation.

### Additional Information
Screenshots that may help in understanding or resolving the issue.

Light mode:-
![image](https://github.com/0ME9A/compressy/assets/83957658/eded9143-eedb-494c-ad25-f2a7146ec9b2)
Dark mode:-
![image](https://github.com/0ME9A/compressy/assets/83957658/597d0f66-5b6d-43e1-93c8-558682fd2ed5)

**Note:** This issue was raised by a user and needs attention to ensure a smooth user experience.

**Comment by kishore881** [comment]
I am not able to reproduce this issue. i think this is incomplete description of the issue. 

the issue happens only if the site is already opened in another private window with theme set to dark mode. then if the user opens the site again in a different tab or different window in private mode, the site automatically loads in dark mode since it is set in local storage but the theme says light mode to start with this is where the inconsistency is coming from
